name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1']
        laravel: ['^5.5', '^5.6', '^5.7', '^5.8', '^6.0', '^7.0', '^8.0', '^9.0']
        exclude:
          - php: 8.1
            laravel: ^5.5
          - php: 8.0
            laravel: ^5.5
          - php: 8.1
            laravel: ^5.6
          - php: 8.0
            laravel: ^5.6
          - php: 8.1
            laravel: ^5.7
          - php: 8.0
            laravel: ^5.7
          - php: 8.1
            laravel: ^5.8
          - php: 8.0
            laravel: ^5.8
          - php: 8.1
            laravel: ^6.0
          - php: 8.1
            laravel: ^7.0
          - php: 7.2
            laravel: ^8.0
          - php: 7.2
            laravel: ^9.0
          - php: 7.3
            laravel: ^9.0
          - php: 7.4
            laravel: ^9.0

    name: Testing on PHP ${{ matrix.php }}  - Testing on Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, bcmath
          tools: composer

      - name: Install PHP dependencies
        run: |
          composer require "illuminate/database=${{ matrix.laravel }}" --no-update
          composer require "illuminate/events=${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress
      - name: Execute tests
        run: vendor/bin/phpunit --verbose

      - name: Run phpunit
        run: composer test
