name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1']

    name: Testing on PHP ${{ matrix.php }}  - Testing on Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, bcmath
          tools: composer

      - name: Install PHP dependencies
        run: composer install

      - name: Execute tests
        run: vendor/bin/phpunit --verbose

      - name: Run phpunit
        run: ./vendor/bin/phpunit
